# secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
  namespace: {{ .Values.namespace.name }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword }}